version: '2'

services:
  app:
    build: .
    env_file:
      - docker/app.env
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - 3000:80

  mysql:
    image: mysql:5.6
    volumes:
      - data-mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

volumes:
  data-mysql: {}
